'use strict';
const crypto=require('crypto'); const digest=v=>crypto.createHash('sha256').update(String(v??''),'utf8').digest('hex');
const subset=(a,b)=>Array.isArray(a)&&Array.isArray(b)&&a.every(x=>b.includes(x)); const same=(a,b)=>String(a??'')===String(b??'');
function evaluateEquivalence(a={},r={}){const bad=[]; if(a.qualified!==true)bad.push('unqualified'); if(a.revoked)bad.push('revoked'); if(!same(a.from_id,r.from_id)||!same(a.from_version,r.from_version)||!same(a.to_id,r.to_id)||!same(a.to_version,r.to_version))bad.push('direction_or_version_mismatch'); if(!same(a.context_id,r.context_id))bad.push('context_mismatch'); if(!subset(r.scope||[],a.scope||[]))bad.push('scope_escape'); return Object.freeze({result:bad.length?'FAIL':'PASS',violations:Object.freeze(bad)});}
function evaluatePathSet(paths=[]){const q=paths.filter(x=>x&&x.result==='PASS'); if(!q.length)return Object.freeze({result:'UNKNOWN',frozen:true}); const vals=new Set(q.map(x=>JSON.stringify(x.destination))); return vals.size===1?Object.freeze({result:'PASS',destination:q[0].destination,frozen:false}):Object.freeze({result:'CONFLICT',frozen:true});}
function evaluateSupersession(a={},r={}){const bad=[]; if(a.qualified!==true||!a.supersession_artifact)bad.push('explicit_qualified_supersession_required'); if(!same(a.predecessor,r.predecessor)||!same(a.successor,r.successor))bad.push('chain_mismatch'); if(!same(a.target_id,r.target_id)||!subset(r.scope||[],a.scope||[]))bad.push('target_or_scope_mismatch'); const now=r.now_ms??Date.now(); if(a.effective_from_ms!=null&&now<a.effective_from_ms)bad.push('not_effective'); if(a.expires_at_ms!=null&&now>=a.expires_at_ms)bad.push('expired'); return Object.freeze({result:bad.length?'FAIL':'PASS',violations:Object.freeze(bad)});}
function evaluateRootEpoch(e={},r={}){const bad=[]; if(!e.root_id||!e.epoch_id||!e.outside_anchor_digest)bad.push('root_material_missing'); if(!same(e.root_id,r.root_id)||!same(e.epoch_id,r.epoch_id))bad.push('inactive_or_wrong_root'); if(!subset(r.scope||[],e.scope||[]))bad.push('root_scope_widening'); if(e.predecessor_epoch&& !e.rotation_artifact)bad.push('rotation_artifact_missing'); if(r.outside_anchor_digest&&!same(e.outside_anchor_digest,r.outside_anchor_digest))bad.push('outside_anchor_mismatch'); const now=r.now_ms??Date.now(); if(e.effective_from_ms!=null&&now<e.effective_from_ms)bad.push('root_not_effective'); if(e.expires_at_ms!=null&&now>=e.expires_at_ms)bad.push('root_expired'); return Object.freeze({result:bad.length?'FAIL':'PASS',violations:Object.freeze(bad),anchor_ref:e.outside_anchor_digest||null});}
function manufactureOutsideAnchor(){return Object.freeze({result:'FAIL',reason:'runtime_cannot_manufacture_outside_anchor'});}
module.exports={digest,evaluateEquivalence,evaluatePathSet,evaluateSupersession,evaluateRootEpoch,manufactureOutsideAnchor};
